[package]
name = "mtl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-recursion = "1.0.5"
clap = { version = "4.4.11", features = ["derive"] }
crossbeam = "0.8.2"
env_logger = "0.10.1"
flate2 = { version = "1.0.28", features = ["zlib"] }
indicatif = { version = "0.17.7", features = ["rayon"] }
itertools = "0.12.0"
libc = "0.2.151"
log = "0.4.20"
md5 = "0.7.0"
rand = "0.8.5"
rayon = "1.8.0"
sha1 = "0.10.6"
thiserror = "1.0.51"
tikv-jemallocator = { version = "0.5.4", optional = true }
tokio = { version = "1.35.0", features = ["rt-multi-thread", "fs", "macros"] }
uuid = { version = "1.6.1", features = ["v4"] }

[dev-dependencies]
criterion = "0.5.1"

[features]
default = []
jemalloc = ["tikv-jemallocator"]

[lib]
name = "mtl"
path = "src/lib.rs"

[[bench]]
name = "md5"
harness = false
